telma_selfcare_prepaid_subscriptioncompany:
    resource: "@TelmaSelfcarePrepaidBundle/Resources/config/routing/subscriptioncompany.yml"
    prefix:   /subscriptioncompany

telma_selfcare_prepaid_company:
    resource: "@TelmaSelfcarePrepaidBundle/Resources/config/routing/company.yml"
    prefix:   /dashboard/company

telma_selfcare_prepaid_user:
    resource: "@TelmaSelfcarePrepaidBundle/Resources/config/routing/user.yml"
    prefix:   /user

telma_selfcare_prepaid_homepage:
    path:     /
    defaults: { _controller: TelmaSelfcarePrepaidBundle:Default:index }

reset_password:
    path:     /reset-mot-de-passe
    defaults: { _controller: TelmaSelfcarePrepaidBundle:User:resetPassword }
